FROM php:8.2-fpm

# Cài đặt các gói cần thiết
RUN apt-get update && apt-get install -y \
    git \
    unzip \
    libpq-dev \
    libonig-dev \
    libzip-dev \
    curl \
    && docker-php-ext-install pdo pdo_mysql mbstring zip

# Cài đặt Node.js (phiên bản 16) và npm
RUN curl -fsSL https://deb.nodesource.com/setup_16.x | bash - && apt-get install -y nodejs

# Cài đặt Composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

# Sao chép mã nguồn
WORKDIR /var/www
COPY . /var/www

# Phân quyền cho thư mục storage và bootstrap/cache
RUN chown -R www-data:www-data /var/www/storage /var/www/bootstrap/cache
