services:
    web:
        container_name: gdt-cashier-web
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        volumes:
            - ./:/var/www/html/gdt-cashier
            #- /var/www/html/gdt-cashier/vendor
            - ~/.composer-docker/cache:/root/.composer/cache:delegated
        ports:
            - ${DOCKER_WEB_PORT}:80
        extra_hosts:
            - ${DOCKER_WEB_HOST}:127.0.0.1
        hostname: ${DOCKER_WEB_HOST}
